import { date } from "quasar";
/**
 * remove sortable column it is used by q-table to sort columns
 * sortOrder : true 'Asc' / 'Desc' Default is 'Asc'
 */
export const countriesColumns = [
  {
    name: "country_name",
    required: true,
    label: "Name",
    align: "left",
    field: "country_name",
    sortBy: true,
    visible: true,
  },
  {
    name: "currency_code",
    align: "left",
    label: "Country Code",
    field: "currency_code",
    sortBy: true,
    visible: true,
  },
  {
    name: "currency_symbol",
    align: "left",
    label: "Symbol",
    field: "currency_symbol",
    sortBy: true,
    visible: false,
  },
  {
    name: "payment_support",
    align: "left",
    label: "Payment",
    field: "payment_support",
    sortBy: true,
    visible: true,
  },
];

export const companyColumns = [
  {
    name: "company_name",
    required: true,
    label: "Name",
    align: "left",
    field: "company_name",
    visible: true,
    sort: { order: true, index: 0 },
  },
  {
    name: "domain",
    label: "Domain",
    align: "left",
    field: "domain",
    visible: true,
    sort: { order: true },
  },
  {
    name: "gst_no",
    label: "GST No",
    align: "left",
    field: "gst_no",
    visible: true,
  },
  {
    name: "state_name",
    required: true,
    label: "State",
    align: "left",
    field: "state_name",
    visible: true,
    sort: { order: true },
  },
  {
    name: "is_inventory",
    label: "Inventory",
    align: "left",
    field: "is_inventory",
    visible: true,
    sort: { order: true },
  },
  {
    name: "extraAttr",
    label: "Extra Attributes",
    align: "left",
    field: "extraAttr",
    visible: false,
    sortBy: false,
  },
];

export const voterColumns = [
  {
    name: "voter_name",
    required: true,
    label: "Name",
    align: "left",
    field: "voter_name",
    visible: true,
    sort: { order: true, index: 0 },
  },
  {
    name: "voter_name_marathi",
    label: "सभासदाचे नाव",
    align: "left",
    field: "voter_name_marathi",
    visible: true,
    sort: { order: true },
  },
  {
    name: "reference_no",
    label: "Account Number",
    align: "left",
    field: "reference_no",
    visible: true,
  },
  {
    name: "mobile",
    required: true,
    label: "Mobile",
    align: "left",
    field: "mobile",
    visible: true,
    sort: { order: true },
  },
  {
    name: "area_name",
    required: true,
    label: "Area",
    align: "left",
    field: "area_name",
    visible: true,
    sort: { order: true },
  },
  {
    name: "city_name",
    required: true,
    label: "City",
    align: "left",
    field: "city_name",
    visible: true,
    sort: { order: true },
  },
];
export const volunteerColumns = [
  {
    name: "volunteer_name",
    required: true,
    label: "Name",
    align: "left",
    field: "volunteer_name",
    visible: true,
    sort: { order: true, index: 0 },
  },
  {
    name: "volunteer_name_marathi",
    label: "नाव",
    align: "left",
    field: "volunteer_name_marathi",
    visible: true,
    sort: { order: true },
  },
  {
    name: "designation",
    label: "Designation",
    align: "left",
    field: "designation",
    visible: true,
    sort: { order: true },
  },
  {
    name: "contact_no",
    label: "Contact",
    align: "left",
    field: "contact_no",
    visible: true,
    sort: { order: true },
  },
  {
    name: "hirarche",
    label: "Order",
    align: "left",
    field: "hirarche",
    visible: true,
    sort: { order: true },
  },
];

export const cityColumns = [
  {
    name: "city_name",
    required: true,
    label: "Name",
    align: "left",
    field: "city_name",
    visible: true,
    sort: { order: true, index: 0 },
  },
  {
    name: "city_name_marathi",
    required: false,
    label: "नाव",
    align: "left",
    field: "city_name_marathi",
    visible: true,
    sort: { order: true },
  },
];

export const areaColumns = [
  {
    name: "area_name",
    required: true,
    label: "Name",
    align: "left",
    field: "area_name",
    visible: true,
    sort: { order: true, index: 0 },
  },
  {
    name: "area_name_marathi",
    required: false,
    label: "नाव",
    align: "left",
    field: "area_name_marathi",
    visible: true,
    sort: { order: true },
  },
  {
    name: "city_name",
    required: false,
    label: "City",
    align: "left",
    field: "city_name",
    visible: true,
    sort: { order: true },
  },
  {
    name: "city_name_marathi",
    required: false,
    label: "नाव",
    align: "left",
    field: "city_name_marathi",
    visible: true,
    sort: { order: true },
  },
];

export const wardColumns = [
  {
    name: "ward_no",
    required: true,
    label: "Ward No",
    align: "left",
    field: "ward_no",
    visible: true,
    sort: { order: true },
  },
  {
    name: "ward_name",
    required: true,
    label: "Name",
    align: "left",
    field: "ward_name",
    visible: true,
    sort: { order: true, index: 0 },
  },
  {
    name: "ward_name_marathi",
    required: false,
    label: "नाव",
    align: "left",
    field: "ward_name_marathi",
    visible: true,
    sort: { order: true },
  },
  {
    name: "manager",
    required: false,
    label: "Booth Manager",
    align: "left",
    field: "manager",
    visible: true,
    sort: { order: true },
  },
];
